---
services: docker

before_install:
    # Upgrade docker version
    # Source: https://docs.travis-ci.com/user/docker/
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
    # Test building docker image
    - docker build -t docker-ansible .

    # Test running the docker container
    - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

    # Verifying the ansible installation
    - docker exec --tty test-container env TERM=xterm ansible --version